spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/New_Reader_DB?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: mipa
    password: mipa
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      root: DEBUG
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

    com:
      mipa:
        ReaderRD:
          Security:
            JwtAuthenticationFilter: DEBUG

pagehelper:
  helper-dialect: mysql
  reasonable: false       # 页码 < 1 自动设置为 1，页码超过总页数自动设置为最后一页
  support-methods-arguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath*:mapper/*.xml


my-settings:
  file-separator: "/"
  secret: "mipa-secret:mipamipamiaowakuwakupikaqiu"
data:
  settings:
    data-net:
      host: "http://10.12.57.22:8080"
    avatars:
      srcDir: "/statics/avatars"
      dstDir: "D:/mipa/files/avatars"
    book-cover-img:
      srcDir: "/statics/bookCoverImgs"
      dstDir: "D:/mipa/files/bookCoverImgs"
