spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/New_Reader_DB?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: mipa
    password: mipa
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      root: DEBUG
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com.mipa:
      service: DEBUG
      websocket: DEBUG


pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath*:mapper/*.xml



